<a href="https://colab.research.google.com/github/Sreejith-t-shaji-40/DATASCIENCE-LAB/blob/main/Matrix_Operations_sreejith.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#  Matrix Operations

#### Matrices

In [ ]:
# Create a matrix using the 'matrix()' function of the 'numpy' module.
import numpy as np
x = np.matrix('1 2 3;4 5 6;7 8 9')
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
# Convert a nested Python list into a matrix using the 'matrix()' function of the 'numpy' module.
y = np.matrix([[1,2,3],[4,5,6],[7,8,9]])
print(y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


#### Matrix Multiplication



$$\begin{bmatrix} 8 & 7 \\ 3	& -5	\\\end{bmatrix} \begin{bmatrix} 3 \\ 2 \\\end{bmatrix}$$

To multiply two matrices, you have to use the `matmul()` function of the `numpy` module. It takes two matrices to be multiplied as inputs and returns a new matrix.

In [ ]:
# Multiplication of the above two matrices.
m1 = np.matrix('8 7;3 -5')
m2 = np.matrix('3; 2')
res = np.matmul(m1, m2)
print(res)

[[38]
 [-1]]


**Note:** The number of columns in the first matrix should be the same as the number of rows in the second matrix. Otherwise, you will get `ValueError`

####  Identity Matrix

In [ ]:
# Create an identity matrix of the dimension 5 and of 'int' type.
i = np.identity(5, dtype =int)
print(i)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


Now let's multiply a square matrix with an identity matrix of the same dimension (say 3).

In [ ]:
# Multiply a square matrix with an identity matrix of the same dimension.
i = np.identity(2, dtype = int)
x = np.matrix('5 7;1 9')
res = np.matmul(i ,x)
print(res)

[[5 7]
 [1 9]]


----

####  Multiplicative Inverse of a Matrix^


Eg. let $A$ be a matrix of dimension $3$

$$A = \begin{bmatrix} 1 & 3 & 3 \\ 1 & 4 & 3 \\ 1 & 3 & 4 \\\end{bmatrix}$$

Then its inverse is

$$A^{-1} = \begin{bmatrix} 7 & - 3 & -3 \\ -1 & 1 & 0 \\ -1 & 0 & 1 \\\end{bmatrix}$$

Both $A$ and $A^{-1}$ have the same dimension.

If you multiply the matrix $A$ with its inverse, you should get the identity matrix of dimension $3$.

$$A^{-1} A = \begin{bmatrix} 7 & - 3 & -3 \\ -1 & 1 & 0 \\ -1 & 0 & 1 \\\end{bmatrix} \begin{bmatrix} 1 & 3 & 3 \\ 1 & 4 & 3 \\ 1 & 3 & 4 \\\end{bmatrix}$$

$$\Rightarrow A^{-1}A = \begin{bmatrix} 7 \times 1 - 3 \times 1 -3 \times 1 &7 \times 3 - 3 \times 4 -3 \times 3 & 7 \times 3 - 3 \times 3 - 3 \times 4 \\ -1 \times 1 + 1 \times 1 + 0 \times 1 & -1 \times 3 + 1 \times 4 + 0 \times 3 & -1 \times 3 + 1 \times 3 + 0 \times 4 \\ -1 \times 1 + 0 \times 1 + 1 \times 1 & -1 \times 3 + 0 \times 4 + 1 \times 3 & -1 \times 3 + 0 \times 3 + 1 \times 4 \\\end{bmatrix}$$

$$\Rightarrow A^{-1}A = \begin{bmatrix} 1 & 0 & 0 \\ 0 & 1 & 0 \\ 0 & 0 & 1 \\\end{bmatrix}$$


In [ ]:
#Multiply the above matrix with its inverse.
n = np.matrix('1 3 3;1 4 3;1 3 4')
iv = np.linalg.inv(n)
res = np.matmul(n , iv)
print(res)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### Determinant of a Matrix^^


$$X = \begin{bmatrix} 8 & 7 \\ 3	& -5 \\\end{bmatrix}$$

 To calculate the determinant value of a square matrix, use the `linalg.det()` function of the `numpy` module.

**Syntax:** `np.linalg.det(a)`

where `a` is some square matrix.

In [ ]:
# Calculate the determinant of the matrix X.
x = np.matrix('8 7; 3 -5')
d=np.linalg.det(x)
print(d)

-60.99999999999995


Let's calculate the determinant of the matrix

$$A = \begin{bmatrix} 1 & 3 & 3 \\ 1 & 4 & 3 \\ 1 & 3 & 4 \\\end{bmatrix}$$

using Python.

In [ ]:
#Calculate the determinant of the above matrix A.
A = np.matrix('1 3 3; 1 4 3;1 3 4')
d = np.linalg.det(A)
print(d)

1.0


In [ ]:
# Calculate the inverse of the above matrix A.
inv = np.linalg.inv(A)
print(inv)

[[ 7. -3. -3.]
 [-1.  1.  0.]
 [-1.  0.  1.]]


In [ ]:
#Create a dictionary to store weatherdata and convert it to a dtaframe
import pandas as pd
weatherdata = { 'Day' :['Monday','Tuesday','wednesday','Thursday','friday','saturday','sunday'],
               'city' :['Kottayam','Alapuzha','vaikom','dubai','chembu','wayanadu','palakadu'],
               'Temprature' :[28, 34, 24, 26, 31, 19, 48],
               'Windspeed' :[50, 56, 70, 88, 99, 33, 60]
               }
wData = pd.DataFrame(weatherdata)
# Display the first five rows of dataframe
wData.head()

#Display the last five rows of dataframe



Day      city  Temprature  Windspeed
0     Monday  Kottayam          28         50
1    Tuesday  Alapuzha          34         56
2  wednesday    vaikom          24         70
3   Thursday     dubai          26         88
4     friday    chembu          31         99

In [ ]:
#Display the last five rows of dataframe
wData.tail()

Day      city  Temprature  Windspeed
2  wednesday    vaikom          24         70
3   Thursday     dubai          26         88
4     friday    chembu          31         99
5   saturday  wayanadu          19         33
6     sunday  palakadu          48         60